version: "2.1"
services:
  server:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/server # volume in host -> $(pwd)/app

    command: [nodemon, ./bin/www]


  db:
    image: mongo
    command: mongod --smallfiles
    # volumes:
    #   - ./mongo/db:/data/db
    # ports:
    #   - "27017:27017"
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3
